// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW9ImQ-W7-pfi_GvWC_RAXtMz6nV1BNic',
    appId: '1:571564010123:web:81e2c94eefaa410fd4028e',
    messagingSenderId: '571564010123',
    projectId: 'projetannuel-f2628',
    authDomain: 'projetannuel-f2628.firebaseapp.com',
    storageBucket: 'projetannuel-f2628.appspot.com',
    measurementId: 'G-7X6QBLMNT4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC35jn-Pk_SFkyr4mKqXOwQprwvPUtngtE',
    appId: '1:571564010123:android:0acaa0e82d59d082d4028e',
    messagingSenderId: '571564010123',
    projectId: 'projetannuel-f2628',
    storageBucket: 'projetannuel-f2628.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDLtCRHrB3aO6T5AkRFX_40PjS86Icz84',
    appId: '1:571564010123:ios:a9f1c0015f839c1cd4028e',
    messagingSenderId: '571564010123',
    projectId: 'projetannuel-f2628',
    storageBucket: 'projetannuel-f2628.appspot.com',
    iosClientId: '571564010123-uq865909moco6o6i5js6rq32kudmotbc.apps.googleusercontent.com',
    iosBundleId: 'com.example.projetAnnuel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDLtCRHrB3aO6T5AkRFX_40PjS86Icz84',
    appId: '1:571564010123:ios:a9f1c0015f839c1cd4028e',
    messagingSenderId: '571564010123',
    projectId: 'projetannuel-f2628',
    storageBucket: 'projetannuel-f2628.appspot.com',
    iosClientId: '571564010123-uq865909moco6o6i5js6rq32kudmotbc.apps.googleusercontent.com',
    iosBundleId: 'com.example.projetAnnuel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAW9ImQ-W7-pfi_GvWC_RAXtMz6nV1BNic',
    appId: '1:571564010123:web:01949a69747d187cd4028e',
    messagingSenderId: '571564010123',
    projectId: 'projetannuel-f2628',
    authDomain: 'projetannuel-f2628.firebaseapp.com',
    storageBucket: 'projetannuel-f2628.appspot.com',
    measurementId: 'G-954VEJD4P5',
  );

}